import fs from 'fs';
import path from 'path';
import { InstallContext } from './types.ts';

export const PRE_HOOK_MARKER = 'graphhub-pre-hook';
export const POST_HOOK_MARKER = 'graphhub-post-hook';

// Shared hook scripts live in ~/.graphhub/hooks/ so every agent references the
// same files regardless of which client installed GraphHub first.
function hooksDir(ctx: InstallContext): string {
  return path.join(ctx.home, '.graphhub', 'hooks');
}

export function sharedPreHookPath(ctx: InstallContext): string {
  return path.join(hooksDir(ctx), 'graphhub-pre-hook.sh');
}

export function sharedPostHookPath(ctx: InstallContext): string {
  return path.join(hooksDir(ctx), 'graphhub-post-hook.sh');
}

/** Write hook shell scripts to ~/.graphhub/hooks/ and return their paths. */
export function writeSharedHookScripts(ctx: InstallContext): { pre: string; post: string } {
  const dir = hooksDir(ctx);
  fs.mkdirSync(dir, { recursive: true });

  const pre = sharedPreHookPath(ctx);
  const post = sharedPostHookPath(ctx);

  fs.writeFileSync(pre, buildPreHookScript(), { mode: 0o755 });
  fs.writeFileSync(post, buildPostHookScript(ctx.graphhubDir), { mode: 0o755 });

  return { pre, post };
}

/** Remove shared hook scripts (called during uninstall if no other agent needs them). */
export function removeSharedHookScripts(ctx: InstallContext): void {
  for (const p of [sharedPreHookPath(ctx), sharedPostHookPath(ctx)]) {
    try { fs.unlinkSync(p); } catch { /* already gone */ }
  }
}

/** Build a Claude Code / Gemini CLI compatible hooks config object. */
export function buildHooksConfig(pre: string, post: string): Record<string, Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>> {
  return {
    PreToolUse: [{
      matcher: 'Glob|Grep|Read',
      hooks: [{ type: 'command', command: `bash "${pre.replace(/\\/g, '/')}"` }],
    }],
    PostToolUse: [{
      matcher: 'Bash',
      hooks: [{ type: 'command', command: `bash "${post.replace(/\\/g, '/')}"` }],
    }],
  };
}

/** Returns true if any existing hook entry references a graphhub hook marker. */
export function hasGraphhubHook(entries: Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>): boolean {
  return entries.some((h) => h.hooks.some((hk) => hk.command.includes(PRE_HOOK_MARKER) || hk.command.includes(POST_HOOK_MARKER)));
}

/** Strip all graphhub hook entries from a hooks map (for uninstall). */
export function stripGraphhubHooks(
  hookMap: Record<string, Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>>,
): Record<string, Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>> {
  const result: typeof hookMap = {};
  for (const [key, entries] of Object.entries(hookMap)) {
    result[key] = entries.filter(
      (h) => !h.hooks.some((hk) => hk.command.includes(PRE_HOOK_MARKER) || hk.command.includes(POST_HOOK_MARKER)),
    );
  }
  return result;
}

/**
 * A concise system instruction injected into agents that don't support bash hooks.
 * Tells the agent to prefer GraphHub MCP tools over raw file search.
 */
export const GRAPHHUB_INSTRUCTIONS = `\
This project uses GraphHub (MCP server: "graphhub") for code intelligence.
When available, prefer these tools over manual file search — they use up to 94% fewer tokens:
  semantic_search   natural-language code search
  search_by_name    exact or fuzzy symbol lookup
  get_context       callers + callees of any function or class
  impact_analysis   blast radius before editing a symbol
  debug_trace       one-shot search + context + next steps
  remember/recall   save and retrieve learnings across sessions
Check for ".graphhub/" in the project root to confirm the index is available.`;

function buildPreHookScript(): string {
  return `#!/bin/bash
# GraphHub PreToolUse hook — auto-generated by graphhub setup, do not edit manually.
# Fires before Glob, Grep, and Read; only activates when a project graph exists.
[ -d ".graphhub" ] || exit 0
echo "GRAPHHUB: graph index found. Prefer MCP tools over file search:"
echo "  semantic_search  — natural language (saves ~94% tokens)"
echo "  search_by_name   — exact or fuzzy symbol lookup"
echo "  get_context      — callers + callees of any function"
echo "  impact_analysis  — blast radius before editing"
echo "  debug_trace      — one-shot search + context + next steps"
`;
}

function buildPostHookScript(graphhubDir: string): string {
  const ghDir = graphhubDir.replace(/\\/g, '/');
  return `#!/bin/bash
# GraphHub PostToolUse hook — auto-generated by graphhub setup, do not edit manually.
# Fires after every Bash call; reindexes the graph in the background on new git commits.
[ -d ".graphhub" ] || exit 0

GRAPHHUB_DIR="${ghDir}"
PROJECT_DIR="$(pwd -P)"
STAMP_FILE="$PROJECT_DIR/.graphhub/.last_index_commit"

CURRENT_COMMIT=$(git rev-parse HEAD 2>/dev/null) || exit 0

if [ -f "$STAMP_FILE" ] && [ "$(cat "$STAMP_FILE" 2>/dev/null)" = "$CURRENT_COMMIT" ]; then
  exit 0
fi

echo "GRAPHHUB: new commit detected — reindexing in background..."
(
  cd "$GRAPHHUB_DIR" && \\
  npx tsx src/index.ts index "$PROJECT_DIR" > /dev/null 2>&1 && \\
  echo "$CURRENT_COMMIT" > "$STAMP_FILE"
) &
`;
}
